force-app/main/default/objects/SavedLink__c/SavedLink__c.object-meta.xml
<CustomObject>
    <label>SavedLink</label>
    <nameField>
        <displayFormat>SL-{YY}-{00000}</displayFormat>
        <label>SavedLink Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SavedLinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SavedLink__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SavedLinkTriggerHandler.cls
public without sharing class SavedLinkTriggerHandler extends TriggerHandler {
  public override void beforeInsert() {
    String userId = UserInfo.getUserId();
    String cQuery = 'SELECT Count() FROM SavedLink__c WHERE OwnerId =:userId';
    Integer userSLCount = Database.countQuery(cQuery);
    //system.debug(userSLCount);
    // Integer userSLCount = Database.countQuery('SELECT Count() FROM SavedLink__c WHERE OwnerId =' + UserInfo.getUserId());
    for(SavedLink__c savedLink : (List<SavedLink__c>) Trigger.new) {
      savedLink.Position__c = userSLCount + 1;
      system.debug(savedLink);
    }
  }
}