force-app/main/default/objects/SavedLink__c/SavedLink__c.object-meta.xml
<CustomObject>
    <label>SavedLink</label>
    <nameField>
        <displayFormat>SL-{YY}-{00000}</displayFormat>
        <label>SavedLink Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SavedLinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SavedLink__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SavedLinksController.cls
public with sharing class SavedLinksController {
    @AuraEnabled(cacheable=true)
    public static SavedLink__c[] getSavedLinks(){
        SavedLink__c[] result = [SELECT Id, Name, Title__c, URL__c, Position__c FROM SavedLink__c WHERE OwnerId = :UserInfo.getUserId() ORDER BY Position__c ASC];
        return result;
    }

    @AuraEnabled
    public static SavedLink__c createSavedLink(String title, String url){
        // Schema.DescribeSObjectResult s = SavedLink__c.sObjectType.getDescribe();
        // Boolean isCreateable = s.isCreateable();
        SavedLink__c newLink = new SavedLink__c();
        if (Schema.sObjectType.SavedLink__c.isCreateable()) {
            Integer countOfSavedLinks = [SELECT COUNT() FROM SavedLink__c WHERE OwnerId =:UserInfo.getUserId()];
            //system.debug('####  ' + CountOfSavedLinks);
            newLink.Title__c = title;
            newLink.URL__c = url;
            newLink.OwnerId = UserInfo.getUserId();
            insert newLink;
        }
        return newLink;
    }
    @AuraEnabled
    public static string deleteSavedLink(String linkId){
        SavedLink__c toDeleteLink = [SELECT Id FROM SavedLink__c WHERE Id =: linkId LIMIT 1];
        if (Schema.sObjectType.SavedLink__c.isDeletable()) {
            delete toDeleteLink;
        }
        return toDeleteLink.Id;
    }
}