force-app/main/default/objects/apikey__c/apikey__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>protected api keys</description>
    <label>apikey</label>
</CustomObject>

force-app/main/default/objects/apikey__c/fields/key__c.field-meta.xml
<CustomField>
    <fullName>key__c</fullName>
    <description>api key</description>
    <label>key</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StockController.cls
public class StockController {
    
    @AuraEnabled
    public static Map<String, Object> getStock(String tickerSymbol) {
        Map<String, Object> results = new Map<String, Object>();
        
        apikey__c cs = apikey__c.getInstance('alphavantage');

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=' + tickerSymbol + '&apikey=' + cs.key__c);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if (response.getStatusCode() == 200) {
            // Deserialize the JSON string into collections of primitive data types.
            results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            system.debug(results);
        }
        return results;
    }
    
    
	//@AuraEnabled
    //public static Map<String, Object> getPrice(String recordId) {
        
    //}
}